services:
  temperature-exporter:
    build: .
    container_name: temperature-exporter
    ports:
      - "1099:8080"
    environment:
      - WEBSOCKET_DELAY=${WEBSOCKET_DELAY}
      - WEBSOCKET_URL=${WEBSOCKET_URL}
      - WEBSOCKET_USER=${WEBSOCKET_USER}
      - WEBSOCKET_PASS=${WEBSOCKET_PASS}
    restart: unless-stopped
