server:
  port: 8080

repeat:
  delay: ${WEBSOCKET_DELAY}

websocket:
  url: ${WEBSOCKET_URL}
  user: ${WEBSOCKET_USER}
  pass: ${WEBSOCKET_PASS}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
